stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/raw
      - src/preprocess.py
    outs:
      - data/processed

  train:
    cmd: echo "Training completed"
    deps:
      - data/processed
      - src/train.py